### ISSUE TITLE
Every time flow-metrics is involved in a fullscreen terminal it slides back to my main screen

### ISSUE THREAD

**Issue by skovsboll** [krukow/vsts-flow-metrics#11]
Not a huge deal breaker, but a small annoyance.

When I run any vsts-flow-metrics command while my terminal is in fullscreen mode, I'm taken back to the main screen. Nothing happens on the main screen though. It breaks the flow a little bit.

Here's a video of it (the right-slide is me, the left-slide is caused by vsts-flow-metrics):

https://www.dropbox.com/s/zj6wv6g4tnuasxi/vsts-flow-metric-returns-to-main-osx-screen.mov?dl=1

I wonder if there's a call somewhere to the  `open`  bash command or a similar system call is being made? That will cause OSX to slide home.

**Comment by krukow** [comment]
@skovsboll please run with `-Djava.awt.headless=true` to avoid this
